// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl4_vHUilnxQlqaL4qAVfLgkfCOj8rnQU',
    appId: '1:811963121147:web:a8ebc6ab724e6baaac3efc',
    messagingSenderId: '811963121147',
    projectId: 'dothithongminh-ff0db',
    authDomain: 'dothithongminh-ff0db.firebaseapp.com',
    databaseURL: 'https://dothithongminh-ff0db.firebaseio.com',
    storageBucket: 'dothithongminh-ff0db.appspot.com',
    measurementId: 'G-RF9GF9MQ1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyCl4_vHUilnxQlqaL4qAVfLgkfCOj8rnQU',
      appId: '1:811963121147:android:da76fc243fa8bc01e7df5e',
      messagingSenderId: '811963121147',
      projectId: 'dothithongminh-ff0db');

  // static const FirebaseOptions ios = FirebaseOptions(   /// old
  //   apiKey: 'AIzaSyCl4_vHUilnxQlqaL4qAVfLgkfCOj8rnQU',
  //   appId: '1:811963121147:ios:0b11ed8263232715ac3efc',
  //   messagingSenderId: '811963121147',
  //   projectId: 'dothithongminh-ff0db',
  //   databaseURL: 'https://dothithongminh-ff0db.firebaseio.com',
  //   storageBucket: 'dothithongminh-ff0db.appspot.com',
  //   androidClientId:
  //       '811963121147-a9p7bj5jlakabp22fo3cbkj7nsmag24e.apps.googleusercontent.com',
  //   iosClientId:
  //       '811963121147-evbjdqq9co9v29pi8jcua8bm7kr4smuu.apps.googleusercontent.com',
  //   iosBundleId: 'io.flutter.plugins.firebase.messaging',
  // );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW4djIV4Zjg_mTWsjzbLJez7sRUr6gEF4',
    appId: '1:550386870495:ios:c9a1a88158ac860884216a',
    messagingSenderId: '550386870495',
    projectId: 'hkdo-c1b66',
    databaseURL: 'https://dothithongminh-ff0db.firebaseio.com',
    storageBucket: 'hkdo-c1b66.appspot.com',
    // androidClientId:
    //     '811963121147-a9p7bj5jlakabp22fo3cbkj7nsmag24e.apps.googleusercontent.com',
    // iosClientId:
    //     '811963121147-evbjdqq9co9v29pi8jcua8bm7kr4smuu.apps.googleusercontent.com',
    iosBundleId: 'com.effect.dothithongminh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHAsf51D0A407EklG1bs-5wA7EbyfNFg0',
    appId: '1:811963121147:ios:0b11ed8263232715ac3efc',
    messagingSenderId: '811963121147',
    projectId: 'dothithongminh-ff0db',
    databaseURL: 'https://dothithongminh-ff0db.firebaseio.com',
    storageBucket: 'dothithongminh-ff0db.appspot.com',
    androidClientId:
        '811963121147-a9p7bj5jlakabp22fo3cbkj7nsmag24e.apps.googleusercontent.com',
    iosClientId:
        '811963121147-evbjdqq9co9v29pi8jcua8bm7kr4smuu.apps.googleusercontent.com',
    iosBundleId: 'io.flutter.plugins.firebase.messaging',
  );
}
